import type { ListingDetails } from "@/components/listing-modal"

export const categories = [
  { name: "Textbooks", count: 234, icon: "textbooks" as const },
  { name: "Furniture", count: 156, icon: "furniture" as const },
  { name: "Electronics", count: 189, icon: "electronics" as const },
  { name: "Bikes", count: 78, icon: "bikes" as const },
  { name: "Clothing", count: 312, icon: "clothing" as const },
  { name: "Kitchen", count: 95, icon: "kitchen" as const },
  { name: "Housing", count: 45, icon: "housing" as const },
  { name: "Other", count: 127, icon: "other" as const },
]

export const listings: ListingDetails[] = [
  {
    id: "1",
    title: "Calculus: Early Transcendentals 8th Edition",
    description: "Used for MATH 151/152. Some highlighting but pages are in great condition. Includes solution manual PDF access code (unused). Perfect for engineering or science majors taking their first calculus sequence.",
    price: 45,
    images: [
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&h=600&fit=crop",
    ],
    location: "West Campus",
    timeAgo: "2 hours ago",
    condition: "Good",
    category: "Textbooks",
    seller: {
      name: "Sarah M.",
      rating: 4.9,
      responseTime: "within 1 hour",
      memberSince: "2024",
    },
  },
  {
    id: "2",
    title: "IKEA MALM Desk - White",
    description: "Perfect desk for dorm or apartment. 55\" wide with cable management and drawer. Minor scratches on top surface but barely noticeable. Must pick up - I can help load into your car!",
    price: 75,
    images: [
      "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1611269154421-4e27233ac5c7?w=600&h=600&fit=crop",
    ],
    location: "North Campus",
    timeAgo: "5 hours ago",
    condition: "Like New",
    category: "Furniture",
    seller: {
      name: "Mike T.",
      rating: 4.7,
      responseTime: "within 2 hours",
      memberSince: "2023",
    },
  },
  {
    id: "3",
    title: "MacBook Pro 14\" M3 - 512GB",
    description: "Selling my MacBook Pro, upgraded to the M3 Max model so don't need this anymore. Includes original charger, box, and AppleCare+ until Dec 2025. Battery health at 94%. No scratches or dents.",
    price: 1450,
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=600&h=600&fit=crop",
    ],
    location: "Engineering Building",
    timeAgo: "1 day ago",
    condition: "Like New",
    category: "Electronics",
    seller: {
      name: "Alex K.",
      rating: 5.0,
      responseTime: "within 30 mins",
      memberSince: "2022",
    },
  },
  {
    id: "4",
    title: "Schwinn Collegiate Vintage Bike",
    description: "Classic green Schwinn from the 70s, fully restored. New tires, brake pads, and chain. Perfect for getting around campus in style. Includes lock and lights.",
    price: 180,
    images: [
      "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=600&h=600&fit=crop",
    ],
    location: "Downtown",
    timeAgo: "3 hours ago",
    condition: "Good",
    category: "Bikes",
    seller: {
      name: "Jordan P.",
      rating: 4.8,
      responseTime: "within 1 hour",
      memberSince: "2023",
    },
  },
  {
    id: "5",
    title: "Organic Chemistry Textbook + Model Kit",
    description: "Klein's Organic Chemistry 4th Edition plus molecular model kit. Both used for one semester. Textbook has minimal highlighting. Model kit is complete with all pieces.",
    price: 65,
    images: [
      "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600&h=600&fit=crop",
    ],
    location: "Science Library",
    timeAgo: "6 hours ago",
    condition: "Good",
    category: "Textbooks",
    seller: {
      name: "Emily R.",
      rating: 4.6,
      responseTime: "within 3 hours",
      memberSince: "2024",
    },
  },
  {
    id: "6",
    title: "Mini Fridge - Perfect for Dorms",
    description: "Compact mini fridge with small freezer compartment. 3.2 cubic feet. Runs quietly and keeps things cold! Moving out and need to sell ASAP.",
    price: 50,
    images: [
      "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=600&h=600&fit=crop",
    ],
    location: "South Quad",
    timeAgo: "1 day ago",
    condition: "Good",
    category: "Kitchen",
    seller: {
      name: "Chris D.",
      rating: 4.5,
      responseTime: "within 4 hours",
      memberSince: "2023",
    },
  },
  {
    id: "7",
    title: "North Face Puffer Jacket - Size M",
    description: "Black 700-fill down jacket. Worn for one season, super warm and in excellent condition. Perfect for those cold walks to class!",
    price: 120,
    images: [
      "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&h=600&fit=crop",
    ],
    location: "Student Union",
    timeAgo: "4 hours ago",
    condition: "Like New",
    category: "Clothing",
    seller: {
      name: "Taylor S.",
      rating: 4.9,
      responseTime: "within 1 hour",
      memberSince: "2022",
    },
  },
  {
    id: "8",
    title: "Sony WH-1000XM5 Headphones",
    description: "Best noise-cancelling headphones on the market. Includes carrying case, cables, and airplane adapter. Only selling because I got AirPods Max as a gift.",
    price: 225,
    images: [
      "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop",
    ],
    location: "Music Building",
    timeAgo: "8 hours ago",
    condition: "Like New",
    category: "Electronics",
    seller: {
      name: "David L.",
      rating: 5.0,
      responseTime: "within 30 mins",
      memberSince: "2021",
    },
  },
  {
    id: "9",
    title: "Free Moving Boxes - Various Sizes",
    description: "Moving out and have about 15 boxes in various sizes. Some are book boxes (heavy duty), others are medium and large. Come pick them up!",
    price: 0,
    isFree: true,
    images: [
      "https://images.unsplash.com/photo-1607166452427-7e4477079cb9?w=600&h=600&fit=crop",
    ],
    location: "Oak Street Apts",
    timeAgo: "30 mins ago",
    condition: "Fair",
    category: "Other",
    seller: {
      name: "Lisa M.",
      rating: 4.3,
      responseTime: "within 2 hours",
      memberSince: "2024",
    },
  },
  {
    id: "10",
    title: "Ergonomic Office Chair",
    description: "Fully adjustable mesh chair with lumbar support and armrests. Great for long study sessions. Paid $350 new, selling cheap because I'm graduating.",
    price: 95,
    images: [
      "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1589364231405-b4b7c61b0c33?w=600&h=600&fit=crop",
    ],
    location: "Grad Housing",
    timeAgo: "12 hours ago",
    condition: "Good",
    category: "Furniture",
    seller: {
      name: "Robert J.",
      rating: 4.7,
      responseTime: "within 1 hour",
      memberSince: "2020",
    },
  },
  {
    id: "11",
    title: "Complete Cooking Set for Students",
    description: "Everything you need: pots, pans, utensils, plates, bowls, cups. Perfect starter kit for your first apartment. Moving in with partner who already has everything.",
    price: 40,
    images: [
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=600&h=600&fit=crop",
    ],
    location: "University Village",
    timeAgo: "2 days ago",
    condition: "Good",
    category: "Kitchen",
    seller: {
      name: "Amanda H.",
      rating: 4.8,
      responseTime: "within 3 hours",
      memberSince: "2023",
    },
  },
  {
    id: "12",
    title: "iPad Air 5th Gen + Apple Pencil 2",
    description: "256GB Space Gray iPad Air with Apple Pencil 2nd gen. Perfect for note-taking! Includes magnetic case and screen protector. Lightly used.",
    price: 520,
    images: [
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1585790050230-5dd28404ccb9?w=600&h=600&fit=crop",
    ],
    location: "Business School",
    timeAgo: "1 day ago",
    condition: "Like New",
    category: "Electronics",
    seller: {
      name: "Nicole W.",
      rating: 4.9,
      responseTime: "within 1 hour",
      memberSince: "2022",
    },
  },
]
